/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.number_guessing;

/**
 *
 * @author hp
 */
public class guess extends javax.swing.JFrame {

    /**
     * Creates new form guess
     */
    public guess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        guesses = new javax.swing.JLabel();
        life = new javax.swing.JLabel();
        scorelbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        show = new javax.swing.JButton();
        unshow = new javax.swing.JButton();
        randomlbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        guess = new javax.swing.JButton();
        bottomlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(240, 60, 223));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("****************Guessing Number****************");

        guesses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guesses.setText("Guesses:");
        guesses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 4));

        life.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        life.setText("Life:");
        life.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0), 4));

        scorelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scorelbl.setText("Score:");
        scorelbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 4));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enter Number from 1 to 100:");

        txtno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnoKeyTyped(evt);
            }
        });

        show.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        show.setText("SHOW");
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        unshow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unshow.setText("UNSHOW");
        unshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unshowMouseClicked(evt);
            }
        });

        randomlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        randomlbl.setText("      ?");
        randomlbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 3));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("New Random Number");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        guess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guess.setText("Guess");
        guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessActionPerformed(evt);
            }
        });

        bottomlbl.setBackground(new java.awt.Color(255, 51, 51));
        bottomlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bottomlbl.setForeground(new java.awt.Color(51, 51, 255));
        bottomlbl.setText("                        ****Try Your Luck****");
        bottomlbl.setToolTipText("");
        bottomlbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 4, true));
        bottomlbl.setDoubleBuffered(true);
        bottomlbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(52, 52, 52)
                                .addComponent(guess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(162, 162, 162)
                                .addComponent(show)
                                .addGap(55, 55, 55)
                                .addComponent(unshow))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(randomlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(scorelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(guesses, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addComponent(life, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(bottomlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guesses, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(life, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scorelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(randomlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unshow, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(bottomlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoKeyTyped
        guess1._integeronly(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoKeyTyped

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        show.setEnabled(false);
        unshow.setEnabled(true);
        randomlbl.setText(String.valueOf(random));// TODO add your handling code here:
    }//GEN-LAST:event_showMouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed

    private void unshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unshowMouseClicked
        show.setEnabled(true);
        unshow.setEnabled(false);
        randomlbl.setText("?");  // TODO add your handling code here:
    }//GEN-LAST:event_unshowMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your han
        randomNew();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessActionPerformed
        guess();
    }//GEN-LAST:event_guessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bottomlbl;
    private javax.swing.JButton guess;
    private javax.swing.JLabel guesses;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel life;
    private javax.swing.JLabel randomlbl;
    private javax.swing.JLabel scorelbl;
    private javax.swing.JButton show;
    private javax.swing.JTextField txtno;
    private javax.swing.JButton unshow;
    // End of variables declaration//GEN-END:variables
guess1 guess1;
private int random=0, bestscore=0,score=0,Correctscore=3;
private byte guessCount=0, lifecount=10, greaterThanError=0,lessThanError=0;
    public void init()
    {
     guess1=new guess1();
     guess1._centerframe(this);
       random=guessNumbers._randomNumber();
       unshow.setEnabled(false);
       life.setText("Life:10");
       
       
    }
    private void randomNew(){
         random=guessNumbers._randomNumber();
         txtno.setText("");
         txtno.requestFocus();
         unshow.setEnabled(false);
         show.setEnabled(true);
         randomlbl.setText("?");
       
    }
    private void guess()
    {
        if(txtno.getText().equals("")){
            guess1._message("please enter your number:",0);
           txtno.requestFocus();
        }
        else if(Integer.parseInt(txtno.getText())>=101||Integer.parseInt(txtno.getText())<1){
             guess1._message("please enter number from 1-100!:",0);
             txtno.setText("");
           txtno.requestFocus();
        }
        else     
        {
          int yournumber=Integer.parseInt(txtno.getText());
          if(yournumber==random)
          {
              guess1._message("YOU WON!\n Additional 3 life was Added!",1);
              score++;
              scorelbl.setText("Score:"+score);
              lifecount+=Correctscore;
              life.setText("Life"+lifecount);
          }
          else
          {
              lifecount--;
              life.setText("Life:"+lifecount);
              hint(random,yournumber);
              //check if reched to 0
              if(lifecount==0)
              {
                  guess1._message("youve used all your life!,\nPlease try again next time",0);
                  System.exit(0);
              }
              
             
          }
          guessCount++;
          guesses.setText("Guesses:"+guessCount);
           
          
        }
        
    }
    private void hint(int _randomnum, int yournumber){
        String mes="";
        if(_randomnum>yournumber){
            lessThanError++;
             mes=messagehint(lessThanError,(byte)1,yournumber);
            bottomlbl.setText(mes);
        }
        else
        {
            greaterThanError++;
               mes=messagehint(greaterThanError,(byte)0,yournumber);
            bottomlbl.setText(mes);
        }
    }
    private String messagehint(byte errorcount,byte errorcatcher,int numguess)
    {
        String message;
        switch(errorcatcher){
            case 1:
                String messagecat[]= {String.valueOf(numguess)+"is less than the number!please be obeservant!",
                  String.valueOf(numguess)+"is less than the number!dont you know how to compute?",
                  String.valueOf(numguess)+"is less than the number!Oh!! Come ON!!",
                  String.valueOf(numguess)+"is less than the number!Im tired of Reminding!"};
                if(errorcount<2){
                    message=String.valueOf(numguess)+"is less than random number!";
                }
                else
                {
                    int randomMes =(int) Math.round(Math.random()*3);
                    message=messagecat[randomMes];
                }
                break;
            default:
                  String messagecat1[]= {String.valueOf(numguess)+"is greater than the number!please be obeservant!",
                  String.valueOf(numguess)+"is greater than the number!dont you know how to compute?",
                  String.valueOf(numguess)+"is greater than the number!Oh!! Come ON!!",
                  String.valueOf(numguess)+"is greater than the number!Im tired of Reminding!"};
                if(errorcount<2){
                    message=String.valueOf(numguess)+"is greater than random number!";
                }
                else
                {
                    int randomMes =(int) Math.round(Math.random()*3);
                    message=messagecat1[randomMes];
                }
                break;
        }
        return message;
    }
}

